'use strict';

const { createCombatActionRuntime } = require('./combat-action-runtime');
const { createCombatAimRuntime } = require('./combat-aim-runtime');
const { createCombatMovementRuntime } = require('./combat-movement-runtime');
const { createCombatTargetRuntime } = require('./combat-target-runtime');

function createCombatRuntime(runtime = {}) {
  const {
    bot,
    cfg,
    safeJsonClone = value => value,
    arrayCount = value => Array.isArray(value) ? value.length : 0,
    formatDistance = value => String(value),
    formatDurationMs = value => String(value),
    actorLabel = value => String(value?.name || value?.id || ''),
    hpDisplay = value => String(value),
    now = () => (typeof performance !== 'undefined' ? performance.now() : Date.now()),
    hypot = Math.hypot,
    dist = () => Infinity,
    speed = () => 0,
    clamp = (value, min, max) => Math.max(min, Math.min(max, value)),
    staminaRemaining = () => NaN,
    staminaExhaustedThreshold = () => 0,
    combatMovementBlockedByStamina = () => false,
    staminaBudgetCoinLeaveSummary = () => '',
    staminaExhaustedWindowLabel = () => '',
    isInvulnerable = () => false,
    isCurrentlyActive = () => false,
    isFiringEntity = () => false,
    isMovingThreat = () => false,
    isAfkProfitTarget = () => false,
    isWhitelistedTarget = () => false,
    hasCombatActivitySignal = () => false,
    isJoinModeActive = () => false,
    hpValue = () => 0,
    combatHpValue = () => 100,
    knownHpValue = () => null,
    dropValue = () => 0,
    isFullHp = () => true,
    isAlive = value => Boolean(value),
    entityFreshEnoughForOffense = () => true,
    normalizeBullet = value => value,
    getBullets = () => [],
    getNativeEntityList = () => [],
    getSelf = () => null,
    classify = () => ({}),
    returnBlockRadius = () => Infinity,
    attackWorthTakingCore = () => false,
    attackWorthTaking = attackWorthTakingCore,
    recordNetworkQualityAttackDamage = () => {},
    summarizeSelf = value => value,
    updateSessionStats = () => {},
    summarizeServerPositionStall = () => null,
    stopMotionSafely = () => {},
    leaveOffline = async () => null,
    activeOfflineLeaveDetail = () => null,
    requestReload = () => {},
    updateBotPanel = () => {},
    summarizeControl = () => null,
    directionTo = () => ({ dx: 0, dy: 0, distance: Infinity }),
    opportunityLongStaminaBudget = () => Infinity,
    scoreEnemyOpportunity = () => -Infinity,
    opportunityEnemyStaminaCost = () => Infinity,
    estimatedKillShots = () => 0,
    opportunityStaminaAffordable = () => false,
    scoreCoinOpportunity = () => -Infinity
  } = runtime;

  const targetRuntime = createCombatTargetRuntime({
    bot,
    cfg,
    staminaBudgetCoinLeaveSummary,
    staminaExhaustedWindowLabel,
    isInvulnerable,
    isCurrentlyActive,
    isFiringEntity,
    isMovingThreat,
    isAfkProfitTarget,
    isWhitelistedTarget,
    hasCombatActivitySignal,
    isJoinModeActive,
    hpValue,
    combatHpValue,
    knownHpValue,
    dropValue,
    isFullHp,
    isAlive,
    entityFreshEnoughForOffense,
    classify,
    returnBlockRadius,
    attackWorthTakingCore,
    attackWorthTaking,
    recordNetworkQualityAttackDamage,
    summarizeSelf,
    updateSessionStats,
    getSelf,
    stopMotionSafely,
    leaveOffline,
    activeOfflineLeaveDetail,
    requestReload,
    updateBotPanel,
    summarizeControl,
    dist,
    speed,
    opportunityLongStaminaBudget,
    scoreEnemyOpportunity,
    opportunityEnemyStaminaCost,
    estimatedKillShots,
    opportunityStaminaAffordable,
    scoreCoinOpportunity,
    combatMotionSamplesWithCurrent: (...args) => aimRuntime.combatMotionSamplesWithCurrent(...args),
    incomingBulletThreat: (...args) => movementRuntime.incomingBulletThreat(...args)
  });

  const movementRuntime = createCombatMovementRuntime({
    bot,
    cfg,
    now,
    hypot,
    dist,
    speed,
    clamp,
    staminaRemaining,
    staminaExhaustedThreshold,
    combatMovementBlockedByStamina,
    isCurrentlyActive,
    isFiringEntity,
    isMovingThreat,
    hpValue,
    dropValue,
    normalizeBullet,
    getBullets,
    ...targetRuntime
  });

  const aimRuntime = createCombatAimRuntime({
    bot,
    cfg,
    now,
    dist,
    speed,
    clamp,
    staminaRemaining,
    staminaExhaustedThreshold,
    isInvulnerable,
    isCurrentlyActive,
    isFiringEntity,
    hpValue,
    combatHpValue,
    knownHpValue,
    dropValue,
    isAlive,
    getNativeEntityList,
    summarizeServerPositionStall,
    ...targetRuntime
  });

  const actionRuntime = createCombatActionRuntime({
    bot,
    cfg,
    formatDurationMs,
    actorLabel,
    hpDisplay,
    dist,
    speed,
    clamp,
    staminaRemaining,
    staminaExhaustedThreshold,
    combatMovementBlockedByStamina,
    isInvulnerable,
    isCurrentlyActive,
    isFiringEntity,
    hpValue,
    combatHpValue,
    knownHpValue,
    summarizeServerPositionStall,
    ...targetRuntime,
    ...movementRuntime,
    ...aimRuntime
  });

  return {
    ...targetRuntime,
    ...movementRuntime,
    ...aimRuntime,
    ...actionRuntime
  };
}

module.exports = {
  createCombatRuntime
};
