'use strict';

const { createOrchestrationSafetyRuntime } = require('./orchestration-safety-runtime');
const { createOrchestrationDecisionRuntime } = require('./orchestration-decision-runtime');
const { createOrchestrationTickRuntime } = require('./orchestration-tick-runtime');

function createOrchestrationRuntime(runtime = {}) {
  const {
    domainContexts = null
  } = runtime;
  const runtimeContext = domainContexts?.flat || runtime;
  const {
    BOT_KEY,
    ENEMY_LEAVE_STATE_KEY,
    LOGIN_SUPPRESS_KEY,
    LOGIN_SUPPRESS_REASON_KEY,
    OFFLINE_LEAVE_STATE_KEY,
    PENDING_EXIT_STATE_KEY,
    activeCombatThreatWaitAction,
    activeEnemyLeaveDetail,
    activeOfflineLeaveDetail,
    actorLabel,
    applyCoinApproachLockUpdate,
    applyCoinProgressAction,
    applyFinalActionArbitration,
    arrayCount,
    assessActionSettlementStall,
    assessOfflineSafety,
    assessServerPositionStall,
    attachCoinDiagnostics,
    attachOpportunisticShot,
    attackWorthTakingCore,
    bot,
    buildCoinAction,
    buildCoinDiagnostics,
    buildCombatAction,
    buildDropMatchedKillCore,
    buildEnemyAction,
    buildMissingHeldOpportunityCore,
    buildNativeCoinSnapshotCore,
    buildNativeEntityMeta,
    buildOpportunisticShotWait,
    buildPostAttackDropWaitAction,
    canPrioritizeHighValueVisibleCoin,
    cfg,
    chooseStableOpportunityCore,
    clearCoinTracking,
    clearCombatEngagement,
    clearExitHoldDetail,
    clearMissingVisibleCoinTarget,
    clearPersistentExitState,
    clearPersistentPendingExitState,
    clearSessionMismatchRecoveryState,
    cloudflareErrorInfo,
    coinBlockedByThreat,
    coinDiagnosticsLimit,
    coinDiagnosticsNearDistance,
    coinDirectionToCore,
    coinMotionCoreOptions,
    coinMotionMetaCore,
    coinPickupAttemptSlowCount,
    coinPickupFailureCount,
    coinRouteCoreOptions,
    coinRouteKey,
    coinStaminaAffordableWithDiagnostic,
    coinTargetCoreOptions,
    coinTargetKeyCore,
    coinThreatDiagnostics,
    combatDodgeOnlyCandidateRange,
    combatHpValue,
    combatTargetCandidateRange,
    combatTickActiveFromState,
    combatTickGapOfflineState,
    controlHasNativeGameSession,
    currentHeldCoinChoice,
    currentHeldCoinRouteChoice,
    dailyStaminaBudgetIsLimitingCore,
    dailyStaminaFinalCoinAction,
    decorateActiveThreat,
    defensiveTargetOverridesEngaged,
    deferredStaminaExhaustionLeave,
    dist,
    dropValue,
    ensureControlWs,
    entityFreshEnoughForOffense,
    exitMotionStopLockRemainingMs,
    finishImportantCombat,
    formatDistance,
    formatDurationMs,
    getBullets,
    getCoins,
    getCurrentUserId,
    getNativeCoinList,
    getNativeEntityList,
    getSelf,
    globalSamplingOutageOfflineState,
    handlePendingExit,
    handleTickReentryCombatGap,
    highValueCoinPriorityAmount,
    highValueCoinPriorityHealthyHp,
    highValueVisibleCoinPriorityNeeded,
    hpDisplay,
    hpValue,
    hypot,
    importantSessionStaminaSpentMs,
    incomingBulletThreat,
    installNativeLoginGateInterceptors,
    installPageGlobal,
    installPageNativeSnapshotObserver,
    isAfkProfitTarget,
    isAlive,
    isAvoidanceThreat,
    isCombatStateForInjuryLeave,
    isConservingStamina,
    isCurrentlyActive,
    isFiringEntity,
    isFullHp,
    isInvulnerable,
    isInvulnerableActive,
    isRecovering,
    isSnapshotCoinWaitAction,
    isSnapshotOnlyCoin,
    isWhitelistedTarget,
    knownHpValue,
    latestEnemyLeaveDisplayReason,
    leaveForCombat,
    leaveForInjury,
    leaveForPursuit,
    leaveOffline,
    liveSessionMismatchTakeoverState,
    logStatus,
    loginSnapshotGateDisplayReason,
    markCoinCollected,
    maybeRecordLoginPoint,
    maybeReloadCloudflareError,
    maybeStartAutoLogin,
    noSelfGameSessionExitState,
    normalizeCoinDrop,
    normalizePendingExitReloadConfirmationCore,
    noteImportantSessionExit,
    noteSelfUnavailableForPostLoginZoom,
    now,
    observeNetworkQualitySelf,
    opportunityCandidateCoreOptions,
    opportunityChoiceCoreOptions,
    opportunityCoinStaminaCost,
    opportunityEnemyStaminaCost,
    opportunityLongStaminaBudget,
    opportunityPriorityTier,
    opportunityWindowStaminaBudget,
    pageGlobal,
    pendingCombatLeaveAction,
    pendingExitIntentForSkippedLeave,
    pendingExitPersistenceCoreHelpers,
    pendingExitSkipNewLeave,
    pickActiveCombatWaitThreat,
    pickBestOpportunity,
    pickBestOpportunityCore,
    pickCoin,
    pickCoinField,
    pickCoinRouteOpportunityCore,
    pickCombatTarget,
    pickDistantCoin,
    pickEngagedCombatTarget,
    pickHighValueVisibleCoin,
    pickNearestDailyStaminaFinalCoinCore,
    pickPostAttackDropCoinCore,
    pickPostAttackDropWaitTargetCore,
    pickProfitableCombatTarget,
    pickRealtimeLocalCoin,
    postAttackDropResolvedAt,
    previousBot,
    readPersistentExitState,
    recordActionSwitchDiagnostics,
    recordCoinFilterDiagnostic,
    recordCombatLogTick,
    recordImportantCombatTick,
    recordIncidentalCoinPickups,
    recordKillHistoryItem,
    recordUnhandledTickError,
    refreshGlobalState,
    rememberAttack,
    rememberCombatEngagement,
    rememberLoginPointDamageThreat,
    rememberOpportunityChoiceCore,
    requestReload,
    requestSessionMismatchRecoveryReload,
    resetOpportunitySwitchLock,
    resetServerPositionStall,
    restoreImportantLogsForRemote,
    restorePersistedCombatLogPendingEntries,
    restorePersistedExitAuditLogs,
    runTickSafely,
    safeCoinCandidates,
    safeJsonClone,
    safeStringify,
    schedulePostLoginZoomOut,
    scoreCoinOpportunity,
    sendActionVelocity,
    sessionMismatchRecoveryReloadSatisfied,
    setLastTarget,
    shootAt,
    shouldClearOpportunityChoiceCore,
    snapshotCoinAgeMs,
    snapshotCoinLocalSuppressRadius,
    snapshotCoinNavigationReasonCore,
    snapshotDataFreshEnough,
    snapshotEntityAllowed,
    speed,
    staleOfflineStaminaHoldContradicted,
    staminaBudgetCoinLeaveAction,
    staminaBudgetCoinLeaveSummary,
    staminaBudgetReloginDelayMs,
    staminaExhaustedWindowLabel,
    startTargetWhitelistPolling,
    stopMotionSafely,
    summarizeBlockedStaminaOpportunityCore,
    summarizeControl,
    summarizeNearestCoinStaminaBudgetExitCore,
    summarizePendingCombatLeave,
    summarizePursuit,
    summarizeSelf,
    summarizeSessionMismatchRecoveryStatus,
    summarizeStamina,
    syncPausedFromPage,
    uniqueVisibleRouteCoinsCore,
    updateBotPanel,
    updateKillHistory,
    updateOpportunityAfkStaminaObservations,
    updatePursuitTracking,
    updateSessionStats,
    visibleCoinSourcesConfirmTargetMissing,
    writePersistentPendingExitStateCore
  } = runtimeContext;

  const {
    markRecentMovement,
    fleeDirection,
    lockedFleeDirection,
    actionMovesTowardThreat,
    isShortSafeCoinAction,
    returnBlockRadius,
    returnBlockExitRadius,
    returnBlockResumeRadius,
    returnBlockSuppressRadius,
    hasReturnBlockThreat,
    markReturnBlockPressure,
    pickReturnBlockPressure,
    returnBlockScanDirection,
    buildReturnBlockScanAction,
    threatKey,
    mergeThreatLists,
    pickReturnBlockThreat,
    blockThreatReturnAction
  } = createOrchestrationSafetyRuntime({
    bot,
    cfg,
    dist,
    hypot,
    isFiringEntity,
    isFullHp,
    isInvulnerableActive,
    now,
    speed
  });
  const orchestrationSafetyContext = {
    markRecentMovement,
    fleeDirection,
    lockedFleeDirection,
    actionMovesTowardThreat,
    isShortSafeCoinAction,
    returnBlockRadius,
    returnBlockExitRadius,
    returnBlockResumeRadius,
    returnBlockSuppressRadius,
    hasReturnBlockThreat,
    markReturnBlockPressure,
    pickReturnBlockPressure,
    returnBlockScanDirection,
    buildReturnBlockScanAction,
    threatKey,
    mergeThreatLists,
    pickReturnBlockThreat,
    blockThreatReturnAction
  };
  const decisionDomainContexts = {
    ...(domainContexts || {}),
    safety: {
      ...((domainContexts && domainContexts.safety) || {}),
      ...orchestrationSafetyContext
    }
  };

  const {
    classify,
    chooseAction
  } = createOrchestrationDecisionRuntime({
    domainContexts: decisionDomainContexts
  });
  const tickDomainContexts = {
    ...decisionDomainContexts,
    decision: {
      ...((decisionDomainContexts && decisionDomainContexts.decision) || {}),
      chooseAction
    }
  };

  const {
    tick,
    startRuntime
  } = createOrchestrationTickRuntime({
    domainContexts: tickDomainContexts
  });

  return {
    markRecentMovement,
    fleeDirection,
    lockedFleeDirection,
    actionMovesTowardThreat,
    isShortSafeCoinAction,
    returnBlockRadius,
    returnBlockExitRadius,
    returnBlockResumeRadius,
    returnBlockSuppressRadius,
    hasReturnBlockThreat,
    markReturnBlockPressure,
    pickReturnBlockPressure,
    returnBlockScanDirection,
    buildReturnBlockScanAction,
    threatKey,
    mergeThreatLists,
    pickReturnBlockThreat,
    blockThreatReturnAction,
    classify,
    chooseAction,
    tick,
    startRuntime
  };
}

module.exports = {
  createOrchestrationRuntime
};
